apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-hw02
  labels:
    app: nginx-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-hw02
  template:
    metadata:
      labels:
        app: nginx-hw02
    spec:
      containers:
      - name:  nginx-hw02-ctr
        image: nginx:1.19.4
        resources:
          limits:
            cpu: 100m
            memory: "256Mi"
          requests:
            cpu: 100m
            memory: "256Mi"
