apiVersion: v1
kind: Service
metadata:
  name: nginx-hw02
spec:
  type: NodePort
  selector:
    app: nginx-hw02
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30000