apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hw02
  labels:
    app: nginx-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-hw02
      version: "1.0.0"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx-hw02
        version: "1.0.0"
    spec:
      containers:
      - name:  nginx-hw02-ctr
        image: nginx:1.19.4
        resources:
          limits:
            cpu: 100m
            memory: "256Mi"
          requests:
            cpu: 100m
            memory: "256Mi"
